### ISSUE TITLE
disableDates prop

### ISSUE THREAD

**Issue by VersityDev** [ShuCh3n/attic-datepicker#1]
Hi can you show me how to make this prop work, I'm having some issues and there's no example to refer to thanks.

**Comment by ShuCh3n** [comment]
Sorry you're right, i forgot to add the example to the documentation

```html
<div class="space-y-2">
  <h4 class="font-bold text-sm">Disable all dates a week before</h4>
  <attic-datepicker :disableDatesBefore="dayjs().subtract(1, 'week')"></attic-datepicker>
</div>

<div class="space-y-2">
  <h4 class="font-bold text-sm">Disable all dates a week after</h4>
  <attic-datepicker :disableDatesAfter="dayjs().add(1, 'week')"></attic-datepicker>
</div>

<div class="space-y-2">
  <h4 class="font-bold text-sm">Disable specific dates ({{ dayjs().add(8, 'days').format('DD MMM YYYY') }}, {{ dayjs().add(25, 'days').format('DD MMM YYYY') }} - {{ dayjs().add(30, 'days').format('DD MMM YYYY') }})</h4>
  <attic-datepicker :disableDates="[dayjs().add(8, 'days'), [dayjs().add(25, 'days').format('DD MMM YYYY'), dayjs().add(30, 'days').format('DD MMM YYYY')]]"></attic-datepicker>
</div>
`

**Comment by JodyBarnard** [comment]
Thank you for the swift reply, that worked perfectly. To avoid me making another issue, may I quickly ask if it's possible to target the background colour of the datepicker itself? It's all pure white and trying to add CSS to the component itself doesn't seem to work: 

![image](https://github.com/ShuCh3n/attic-datepicker/assets/104017869/eaea2b17-a4c8-49ea-b3b6-3f8119ca5e6b)
